### ISSUE TITLE
BruschettaTool.exe

### ISSUE THREAD

**Issue by confuix** [whid-injector/BRUSCHETTA-board#2]
Fining 2 issues with the  BruschettaTool.exe(Windows) 
1.) The SPI/IC2 FLASH MEMORIES PROGRAMMER does not allow the flashing of Length 0x 2001 or greater

2) Performing Flash Verify  return
[10] data (FF FF FF ...)
[10] stamp (12 A0 etc ...)
mismatch ...
3)
- Basically I dont think my ic is flashing!
 -Is there a help manual for the Tool or help section?
 -Is there a version for Linux.

**Comment by whid-injector** [comment]
That Tool is based on the WCH's sources that you can download here: https://www.wch-ic.com/downloads/CH347EVT_ZIP.html
Specifically in this subdirectory: CH347EVT.ZIP\CH347EVT\TOOLS\CH347Demo
Despite is there and kinda working... I have never trusted it too much.
I always use other more stable FOSS tools on Linux with the BRUSCHETTA:
- Flashrom for SPI
- OpenOCD for JTAG 
- Ch347eeprom for I2C
- Screen for the UART
https://github.com/whid-injector/BRUSCHETTA-Board?tab=readme-ov-file#linux

P.S. In case you need SWD... despite I have never thought to add it at the beginning... due to some hw conntraints while using the level shifters... I recently managed to get some support from WCH I got it working at 3.3V by phisically bypassing the level-shifters... https://x.com/whid_ninja/status/1752335921637183999?s=20
If interested, let me know and I can send the instructions and the firmware for the chipset.

Overall, for you issue I would recommend to try out the linux tools.
In case you will face again issues... please open another issue and provide more details about the exact I2C or SPI IC and rest of details I usually need for troubleshooting: https://github.com/whid-injector/BRUSCHETTA-board/blob/main/README.md#how-to-report-bugs
